version: "3.9"

services:
  app:
    image: node-app
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis
    build: .
    volumes:  
    - ./java:/app/java
    ports:
      - "3000:3000"
  redis:
    image: redis:6.2.5-alpine
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"


volumes:
  redis-data:

