version: "3.9"

services:
  app:
    image: codetester-node
    stdin_open: true 
    tty: true        
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis
    build: .
    volumes:  
    - ./java:/app/java
    ports:
      - "3000:3000"
  redis:
    image: redis:7.2.4-alpine
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"


volumes:
  redis-data:

