services:
  app:    
    build: 
      context: .
      target: dev
    volumes:
      - ./java:/java/
      - type: bind
        source: .
        target: /app/
    ports:
      - "3000:3000" 
      - "9229:9229"  

volumes:
  java:
