version: "3.9"

services:
  app:    
    build: 
      context: .
      target: dev
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis
    volumes:
      - ./java:/java/
      - type: bind
        source: .
        target: /app/
    ports:
      - "3000:3000" 
      - "9229:9229"  

  redis:
    image: redis:7.2.4-alpine
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"

volumes:
  redis-data:
  java: