version: "3.9"

services:
  app:    
    build: .
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis
    volumes:
      - ./java:/java/
    ports:
      - "3000:3000"

  redis:
    image: redis:7.2.4-alpine
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"

volumes:
  redis-data:
  java: