
services:
  app:    
    build:
      context: .
      target: build 
    command: npm run dev
    hostname: app
    environment:
      - NODE_ENV=development
      - REDIS_HOST=redis
    depends_on:
      - redis
    volumes:
      - ./java:/java/
      - type: bind
        source: .
        target: /app/
      - java:/app/java/
    ports:
      - "3000:3000"

  maven: 
    image: maven:3.9.9-amazoncorretto-23-alpine
    volumes:
      - ./java:/java/
    hostname: maven
        
  redis:
    image: redis:7.2.4-alpine
    hostname: queue
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"

volumes:
  redis-data:
  java:
