version: "3.9"

services:
  app:    
    build:
      context: .
      target: prod
    network_mode: "host"
    environment:
      - REDIS_HOST=redis
    healthcheck:
      test: curl -f http://localhost:3000/sys/health || exit 1
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 20s
    labels:
      - "autoheal=true"
    depends_on:
      - redis
    volumes:
      - ./java:/app/java/
    ports:
      - "3000:3000"

  redis:
    image: redis:7.2.4-alpine
    healthcheck:
      test: [ "CMD", "redis-cli","ping" ]
      interval: 5s
      timeout: 3s
      retries: 3
    labels:
      - "autoheal=true"
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"

  autoheal:
    image: willfarrell/autoheal:latest
    tty: true
    environment:
      - AUTOHEAL_INTERVAL=15
      - AUTOHEAL_START_PERIOD=20
      - CURL_TIMEOUT=15 
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  redis-data:
  java:
  autoheal:
